name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build & test

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [release, debug]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - name: Setup premake
      uses: abel0b/setup-premake@v1

    # Linux & MacOS-specific build steps
    - name: Build (gmake)
      if: runner.os != 'Windows'
      run: |
        premake5 gmake
        make clean
        make all config=${{ matrix.configuration }}
    - name: Test (gmake)
      if: runner.os != 'Windows'
      run: ./bin/test

    # Windows-specific build steps
    - name: Add msbuild to PATH
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '16.1.0'
    - name: Build (vs2019)
      if: runner.os == 'Windows'
      run: |
        premake5 vs2019
        msbuild reliable.sln -nologo -m -t:Clean  -p:Configuration=${{ matrix.configuration }}
        msbuild reliable.sln -nologo -m -p:Configuration=${{ matrix.configuration }}
    - name: Test (vs2019)
      if: runner.os == 'Windows'
      run: "& ./bin/${{ matrix.configuration }}/test.exe"